version: "3"

services:

  nginx:
    image: 'nginx:stable'
    volumes:
      - sockets:/sockets/
      - ./nginx/default.dev.conf:/etc/nginx/nginx.conf
      - ./config/services.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - 80:80

  database:
    image: 'postgres:latest'
    env_file: &envfile
      - ./config/default.env
    volumes:
      - ../install/create_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  backend:
    image: 'earth_grid_backend:dev'
    command: uwsgi app.ini
    env_file: *envfile
    volumes:
      - sockets:/sockets/
      - ./logs:/logs
      - ./keys:/keys
      - ./config/app.ini:/earth_grid/app.ini
    depends_on:
      - database

  chunk_daemon:
    image: 'chunk_daemon:dev'
    env_file: *envfile
    volumes:
      - ./logs:/logs
    environment:
      - BROKER_USERNAME=chunk_daemon
      - BROKER_PASSWORD=chunk_daemon
      - LOG_PATH=/logs/chunk_daemon.log
    depends_on:
      - broker

  broker:
    build: ../mosquitto
    depends_on:
      - database
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  sockets:
    driver: local